### ISSUE TITLE
Create all the tables in the supabase database

### ISSUE THREAD

**Issue by Nahom-web** [supabase-code-share/code-share#30]
**DRAFT**

Tables:

1. Snippet (snippetId - primary id, title - varchar, like - boolean, visibility - boolean, userId - Foreign Key, codeId - Foreign Key)
2. Code (codeId - primary key, codeBlock - varchar, language - Foreign Key)
3. Tag (tagId - primary id, name - varchar, snippetId - Foreign Key)
4. User (userId - primary id, username - varchar, email - email, password - varchar)
5. Comment (commentId - primary id, text - varchar, snippetId - foreign key)
6. Following (userId - primary id, followingUserId - Foreign Key)
7. Language (languageId - primary key, name - varchar, abbreviation - varchar, image - varchar)

**Comment by darkh12** [comment]
Tables:

    Snippet (snippetId - primary id, title - varchar, like - boolean, visibility - boolean, userId - Foreign Key, codeBlock - varchar)
    Tag (tagId - primary id, name - varchar, snippetId - Foreign Key)
    User (userId - primary id, username - varchar, email - email, password - varchar)
    Comment (commentId - primary id, text - varchar, snippetId - foreign key, userId - Foreign Key)
    Following (userId - primary id, followingUserId - Foreign Key)
